# Generated by Django 4.1.3 on 2022-11-20 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='debt',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='Debt',
        ),
    ]
