# Generated by Django 4.1.3 on 2022-11-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_assesment'),
    ]

    operations = [
        migrations.AddField(
            model_name='hire',
            name='hire_date',
            field=models.DateField(null=True),
        ),
        migrations.RemoveField(
            model_name='hire',
            name='book',
        ),
        migrations.AddField(
            model_name='hire',
            name='book',
            field=models.ManyToManyField(to='base.book'),
        ),
    ]
