# Generated by Django 4.1.3 on 2022-11-23 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_book_image_remove_hire_book_hire_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.status'),
        ),
    ]
