# Generated by Django 4.1.3 on 2022-11-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='login',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
