# Generated by Django 4.1.3 on 2022-11-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_client_login_client_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='release_year',
            field=models.PositiveIntegerField(),
        ),
    ]
