# Generated by Django 4.1.3 on 2022-11-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_release_release_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='hire_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='return_date',
            field=models.DateField(null=True),
        ),
    ]
