# Generated by Django 4.1.3 on 2022-11-27 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_status_hire_date_alter_status_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.release'),
        ),
    ]
